name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - default
          - windows-x86_64
          - macos-x86_64
          - macos-aarch64
          - linux-x86_64-gnu
          - linux-aarch64-gnu
          - linux-x86_64-musl
          - linux-aarch64-musl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build target
        run: nix build .#${{ matrix.target }}

      - name: Package artifacts
        run: |
          mkdir -p dist
          nix develop .#default -c bash -c '
            for file in result/lib/*; do
              filename=$(basename "$file")
              name="${filename%.*}"
              ext="${filename##*.}"
              
              cp "$file" "dist/${name}-${{ matrix.target }}.${ext}"
              
              cd result/lib
              
              # Standardize the archive name to always start with zslay instead of libzslay
              archivename="zslay-${{ matrix.target }}"
              
              tar -cjf "../../dist/${archivename}.tar.bz2" "$filename"
              tar -czf "../../dist/${archivename}.tar.gz" "$filename"
              tar -cJf "../../dist/${archivename}.tar.xz" "$filename"
              cd ../..
            done
          '

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: zslay-${{ matrix.target }}
          path: dist/*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    environment: Production Release
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*
