name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**/*.zig'
      - '**/*.zon'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.zig'
      - '**/*.zon'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run zig build test
        run: nix develop -c zig build test
